### ISSUE TITLE
Replace LaTeX equations with Typst syntax

### ISSUE THREAD

**Issue by thibaultdouzon** [fenjalien/obsidian-typst#1]
Hi, thanks for your work which looks amazing.

This issue is about a question / feature request:
Would it be possible for this plugin to compile Obsidian equations with Typst instead the default?

**Comment by fenjalien** [comment]
Hi! Thanks for checking this out :)

I'm not sure if it is possible to override the equation syntax, I'll have to look into it.

**Comment by fenjalien** [comment]
Well uh have a look at the latest release!
