### ISSUE TITLE
How to change math font?

### ISSUE THREAD

**Issue by vultix** [fenjalien/obsidian-typst#11]
I'm trying to switch my math font to use firamath: https://github.com/firamath/firamath

I have installed firamath locally to my system, enabled "Search System Fonts", and reloaded the plugin.

My math block preamble contains this line:
```typst
#show math.equation: set text(font: "Fira Math")
```

My code blocks look broken however:
<img width="448" alt="image" src="https://github.com/fenjalien/obsidian-typst/assets/5114062/3cae06f1-bef8-4518-af91-0fee449e5cc3">

I've tried many different math fonts, and there doesn't appear to be any change.  Any suggestions?

**Comment by fenjalien** [comment]
Your font issue is entirely my fault, I missed out the line that gets the system fonts sorry about that. By the way the you don't need a show rule for equations in the math preamble as it only gets prepended to math blocks. It won't affect code blocks.

Why your code block looks like that I do not know with out your source.

**Comment by fenjalien** [comment]
Latest version (0.5.1) should renable loading of system fonts. I've improved the method/ui as well.

also I was wrong you do need a show rule to set the math font...
