### ISSUE TITLE
New renderer fails in preview mode sometimes

### ISSUE THREAD

**Issue by OverHash** [fenjalien/obsidian-typst#12]
Just updated from the previous version of this plugin and it appears to fail to render some typst blocks in preview mode:
![image](https://github.com/fenjalien/obsidian-typst/assets/46231745/61c6bcd0-2535-4a66-9616-b8385b0e4c2f)

In edit mode (working correctly):

![image](https://github.com/fenjalien/obsidian-typst/assets/46231745/71831be3-3fe5-49c0-beee-5901556463b6)

The raw source:
![image](https://github.com/fenjalien/obsidian-typst/assets/46231745/9cde338d-ce38-43d9-b28a-baf0b44a5d4a)

I can't seem to find a solid repro for this issue, but it appears to happen quite consistently in one vault.
The full error is
```
Uncaught ["unknown variable: NaNpt"]
```

Strangely, modifying the source typst block which fails to render, toggling to preview, and changing back to the original source will allow for it to render correctly (for a while).. Is this a cache issue somehow?

I notice that for a given page, the content at the top is much more likely to render successfully than the content at the bottom. It seems to be arbitrary where the content will fail to render -- so seems like there is a race condition almost going on somewhere.

**Comment by OverHash** [comment]
Perhaps it's something to do with this section of code..

https://github.com/fenjalien/obsidian-typst/blob/f01148cd8c517d615ce98750bd648c9c611ba8a9/main.ts#L209-L219

Specifically,
```ts
const pxToPt = (px: number) => (px * dpr * (72 / 96)).toString() + "pt" 
```

**Comment by fenjalien** [comment]
I can't seem to reproduce it from the source you've given, but as you've said it appears to be rare. If you see it happen again can you open the console (Ctrl+shift+I) show me the logs/erros in there?

Its not `pxToPt`'s fault its either `size` or `fontSize` being 0 or NaN which shouldn't necessarily be possible...

Have you also modified the preambles in anyway?

**Comment by OverHash** [comment]
I can reproduce this in a new plain vault with Typst Renderer installed and the math override option turned on.

From the developer console:
![image](https://github.com/fenjalien/obsidian-typst/assets/46231745/79ff27e0-578d-4ae5-b424-677b09b09978)

```
Uncaught ["unknown variable: NaNpt"]     plugin:typst:89 
> eval @ plugin:typst:89

Uncaught ["unknown variable: NaNpt"]     1eb76e4a-8651-4f2d-a8bf-c5b19ad17424:1
```

It looks like the Typst renderer gets particularly tripped up after it successfully [embeds another note](https://help.obsidian.md/Linking+notes+and+files/Embedding+files):
```md
# Asymptotic Notation Rules
- We can **drop constants**: If $c > 0$ then $c f$ is $Theta(f)$.

![Big o Types](big-o-types)

# Asymptotic Notation Rules
- We can **drop constants**: If $c > 0$ then $c f$ is $Theta(f)$.
```
In this example, the first bullet point will render successfully, but the latter will not. I need to have a decent amount of notes before and after this section of my note file before the Typst renderer will fail.

Let me know how you would like me to transmit you the obsidian repro of this (I'd rather not share it publicly on GitHub) -- e.g., through a GPG public key I can sign to or if you're on the Typst Discord.

**Comment by OverHash** [comment]
Just added a debug statement in the piece of the code that I referenced in my comment -- the output after the embedded note part of my note is as expected:
```
path="/586f8912-f3a8-4455-8a4a-3729469c2cc1.typ"

source="#set page(margin: 0pt)
#set align(horizon)
$c > 0$"

size="NaN"
display="false"
fontSize="NaN"
pxToPtSize="NaNpt"
pxToPtFontSize="NaNpt"
```
So looks like `size` and `fontSize` is `NaN` sometimes.

**Comment by OverHash** [comment]
Just sent the repro files in Discord.

**Comment by fenjalien** [comment]
I could reproduce the error with the supplied reproduction files, as of https://github.com/fenjalien/obsidian-typst/commit/05b1a9a9a09cc66bf765e7d8da3e7fb81b2e5adc the error no longer occurs so this is fixed :)

**Comment by OverHash** [comment]
Thanks!
