### ISSUE TITLE
Inline math blocks do not scale with zoom

### ISSUE THREAD

**Issue by feelingnothing** [fenjalien/obsidian-typst#20]
Happens when I zoom in with touchpad on my laptop
![image](https://github.com/fenjalien/obsidian-typst/assets/47575622/b94831b6-0f1f-4207-b11a-9d50d38235ea)
![image](https://github.com/fenjalien/obsidian-typst/assets/47575622/f24bf4f1-a763-451a-b858-d7171099941e)

**Comment by fenjalien** [comment]
Thanks for the bug! Does the issue also happen when you use the zoom in command?

**Comment by fenjalien** [comment]
Okay just tried it on a laptop and I can reproduce this issue. It looks like zooming with a touch pad changes the font size not the overall zoom level. The Typst elements currently only resize on zoom level change.

If you do want to continue using touchpad zoom add the following line to your math preamble:
```
#show math.equation: set text(size: SIZE)
```
and whenever you change the zoom you will need to cause the element to be re-rendered which can be done by placing your cursor in the source.

I'll definitely fix this in the next release :)
