### ISSUE TITLE
Issue when rendering `%` in inline equations

### ISSUE THREAD

**Issue by ayejay-nz** [fenjalien/obsidian-typst#21]
I was trying to render the inline equation `x_1 = 0 "% Initial condition"`, however this gives the following error: 
![image](https://github.com/fenjalien/obsidian-typst/assets/55215693/3192b610-c438-4bb6-845f-c6e931a4136b).
If I try to instead write the equation as `x_1 = 0 "\% Initial condition"`, it renders, however there is still a backslash in the rendered equation: 
![image](https://github.com/fenjalien/obsidian-typst/assets/55215693/b4cb7246-34b0-4190-b8b8-28e72e1f60db). 
The first equation renders correctly using the VSCode Typst LSP, so it seems that the `%` breaks the rendering in the obsidian extension.
I am using the default settings for the extension with the Latex Suite extension installed.

**Comment by fenjalien** [comment]
Thanks :) I've been able to reproduce this and I think this is to do with Obsidian using `%` as a comment syntax in an equation.  Although I'm not eniterly sure why its throwing an unclosed delimiter I'll investigate it further before closing this. I really need to sort out better error output.

As a work-around use Typst's percent symbol:
``` 
$x_1 = 0 percent "Initial condition"$
```
![image](https://github.com/fenjalien/obsidian-typst/assets/34489450/0bbd4f7f-2506-4b92-a6cc-298f6c7b78a1)
