### ISSUE TITLE
Can't get example to work

### ISSUE THREAD

**Issue by Flecart** [fenjalien/obsidian-typst#22]
I just copy pasted the example but can't get it to work
First image in editing mode, second in view mode.
![image](https://github.com/fenjalien/obsidian-typst/assets/63465494/b28f2416-8d6e-409d-9f58-ea90c5734550)
![image](https://github.com/fenjalien/obsidian-typst/assets/63465494/406ef585-70d2-4090-8090-29caa88c30e1)

**Comment by fenjalien** [comment]
It looks like something weird happens between copying from github and pasting to obsidian. It seems to work okay if you copy the contents inside the raw syntax (` ``` `)

**Comment by Flecart** [comment]
Yes, copying the contents inside works!
