### ISSUE TITLE
Set text fill according to theme

### ISSUE THREAD

**Issue by kchousos** [fenjalien/obsidian-typst#23]
Hello there! I'm testing out your package and so far it works wonderfully. The only caveat is that since I sync Obsidian's theme to my system theme, which changes throughout the day, at least half the time the text color is wrong. Is there any solution to this? Thanks in advance.

**Comment by fenjalien** [comment]
In the plugin's current state not easily sorry. I'm planning on using Typst's new SVG export for the next release so it could interact with the current theme through that but that might take a lil bit.

That being said if you are desparate you could read a file with Typst that says which theme to use, and have a script running in the background that changes it at the correct time?

**Comment by kchousos** [comment]
Understandable. It's ok, I will wait for the svg feature. Thanks for the great package!
