### ISSUE TITLE
typst text's are not readable in light mode

### ISSUE THREAD

**Issue by toprak** [fenjalien/obsidian-typst#24]
![2023-08-30-213320_1477x209_scrot](https://github.com/fenjalien/obsidian-typst/assets/43301560/4f4db4e9-c0bb-4e95-a1d8-a776de27a039)

**Comment by fenjalien** [comment]
It'll be because the font colour is set to `white` in the first line of the shared preamble. Setting it to `black` makes the text readable:
```
#set text(fill: black, ...)
```
![image](https://github.com/fenjalien/obsidian-typst/assets/34489450/267953c1-3272-4160-97fe-fae61a2c16dc)

**Comment by kwinso** [comment]
I think it would be great to make this plugin follow obsidian's theme in the future

**Comment by fenjalien** [comment]
As of 0.6.0, there is a `THEME` variable which can be either `"light"` or `"dark"` depending on the theme's mode. @toprak does this fix your issue?

**Comment by toprak** [comment]
@fenjalien I dont have any idea how to use variable

**Comment by fenjalien** [comment]
Sorry, I meant in the preambles https://github.com/fenjalien/obsidian-typst#preambles.
Something like this in the shared preamble should work:
```
if THEME == "dark" {
  set text(white)
} else {
  set text(black)
}
```

**Comment by Alan-Kuan** [comment]
> Sorry, I meant in the preambles https://github.com/fenjalien/obsidian-typst#preambles. Something like this in the shared preamble should work:
> 
> ```
> if THEME == "dark" {
>   set text(white)
> } else {
>   set text(black)
> }
> ```

I found your code will not work properly.

It should be like this one.
```typst
#let color = black
#if THEME == "dark" {
  color = white
}
#set text(fill: color, size: SIZE)
```

**Comment by toprak** [comment]
@fenjalien sorry for late reply i was asleep
```#let color = black
#if THEME == "dark" {
  color = white
}
#set text(fill: color, size: SIZE)```
fixed my issue
