### ISSUE TITLE
Enabling plugin does not work on mobile

### ISSUE THREAD

**Issue by AgathaSorceress** [fenjalien/obsidian-typst#27]
The plugin installs successfully, but when trying to enable it, I get this error:
```
Plugin failure: typst TypeError: Cannot destructure property 'pathToFileURL' of 'require(...)' as it is undefined.
    at node_modules/svgo/lib/svgo-node.js (plugin:typst:37188:11)
```
The same error does not appear when enabling the plugin on desktop. I have tried both installing the 0.6.0 version of the plugin through **Settings** → **Community plugins** and by manually copying the files from the latest GitHub release to the plugin folder.

Tested with Obsidian version 1.4.9 (108) on Android 13

**Comment by fenjalien** [comment]
Thanks for the report! Turns out I was using the wrong distribution of `svgo` which requires node which isn't available on mobile. It'll be fixed in the next released.
