### ISSUE TITLE
Register as a community plugin

### ISSUE THREAD

**Issue by vultix** [fenjalien/obsidian-typst#3]
Thank you for this! I find typst so much more enjoyable than latex for writing math equations. The only thing I'm missing is the ability to use this plugin on my phone to view typst equations (I use obsidian sync so I can sync to my phone).  

Making this an official community plugin would make that possible.

**Comment by vultix** [comment]
Looks like this can be done by making a pull request [here](https://github.com/obsidianmd/obsidian-releases)

**Comment by fenjalien** [comment]
Hi I'm glad you're enjoying it :) and I've finally made the PR! https://github.com/obsidianmd/obsidian-releases/pull/1996

I'll close this once it gets submitted!

**Comment by Supercip971** [comment]
Apparently they don't like having obsidian in the name :/

**Comment by fenjalien** [comment]
Its been accepted!
