### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by N4tus** [fenjalien/obsidian-typst#32]
I want to use a package with `#import "@preview/quill:0.2.0": *` but I just get an error
```
Error: package not found (searched for @preview/quill:0.2.0)
    ╭─[/path/to/file.md:13:9]
    │
 13 │ #import "@preview/quill:0.2.0": *
    │         ──────────────────────  
    │                                  
────╯
```  

I have used the typst cli to compile a .typ file with that content which downloaded the package to `~/.cache/typst/packages/preview/quill/0.2.0/`. And looking in my file directory it is there. Do I need to download the file differently? Or is there an issue with this plugin?

**Comment by fenjalien** [comment]
This should be fixed by #30, I forgot to update the path :/
