### ISSUE TITLE
Slow loading times

### ISSUE THREAD

**Issue by Sinono3** [fenjalien/obsidian-typst#34]
Hi. When I'm loading Obsidian on my PC and phone, the slowest plugin to load by far is obsidian-typst. In PC this isn't really a problem, but sometimes on mobile when I want to quickly pull up obsidian it does add 3 seconds of loading time (2852ms).

![image](https://github.com/fenjalien/obsidian-typst/assets/8389938/2e22319f-766f-42db-b0d9-4f229214d065)

I was wondering if there's any way this could be improved. Maybe we can do some lazy loading or something like that?
I have never written a plugin for Typst, so pardon my ignorance.

**Comment by fenjalien** [comment]
I agree I can find the plugin taking considerably longer than others in my vault to load. I would guess this is down to how the web assembly is being parsed and compiled (this is also why the plugin is so big). There are certainly better ways to do it but Obsidian is very restrictive and it took me ages to find a way that works relaibly. That said I do have a few other ideas but I need to try them out first.

For lazy loading, I think it should be possible? I'll need to confirm where the big slow down is and it might be possible to move it or do it in the background but I'm not sure.

**Comment by fenjalien** [comment]
Fixed with 0.8.0

**Comment by Sinono3** [comment]
Huge thanks! It takes up to 300-400ms on my computer after the update. Now I can fully integrate Typst into my vault :)
