### ISSUE TITLE
math in titles

### ISSUE THREAD

**Issue by joleeee** [fenjalien/obsidian-typst#39]
when using typst in titles, it's not rendered as big as it should be

```md
# Big Theta - $Theta$
```

Text:
<img width="280" alt="image" src="https://github.com/fenjalien/obsidian-typst/assets/24441708/8ba84e8c-d185-4bc4-ab0a-018e7d217e6e">

Rendered:
<img width="161" alt="image" src="https://github.com/fenjalien/obsidian-typst/assets/24441708/cfeeea7d-452d-4f5e-80e1-426cd6e449b7">

**Comment by fenjalien** [comment]
Not sure if this really is a bug or working as intended. Math blocks have no context of where they are, so extra styling is incredibly difficult to apply. We could get more context by using a codemirror extension but I haven't found a way to completely stop Obsidian's own math blocks.

**Comment by joleeee** [comment]
i mean the built in latex math blocks work fine in titles so i definitely think this is a bug

**Comment by Enter-tainer** [comment]
> Not sure if this really is a bug or working as intended. Math blocks have no context of where they are, so extra styling is incredibly difficult to apply. We could get more context by using a codemirror extension but I haven't found a way to completely stop Obsidian's own math blocks.

Hi I'm doing similar thing last week(rendering typst to svg and embed them in markdown). To solve this you need to adjust the svg: by changing the unit of its height and width to `em`, the svg will automatically scale itself.

Code here: https://github.com/Myriad-Dreamin/typst.ts/blob/main/projects/rehype-typst/lib/index.js#L116

And this is how it looks like 
![image](https://github.com/fenjalien/obsidian-typst/assets/25521218/55edf6d6-6782-4710-8e9c-385184c68563)

**Comment by Enter-tainer** [comment]
Also I see currently the css is set to
```
.typst-doc {
    vertical-align: bottom;
}
```

There can be better control of this by querying the location of text baseline in typst and set `vertical-align` according to it.

**Comment by Enter-tainer** [comment]
I guess the optimize svg thing is no longer needed too because currently typst use a stable id to name glyphs so there is no collisions now.

**Comment by joleeee** [comment]
I guess related is:
```md
some vec $vec(1,2,3)$.
```
renders as
<img width="198" alt="image" src="https://github.com/fenjalien/obsidian-typst/assets/24441708/82f791c3-224e-47c5-b0c9-113f035c60b9">

meawhile without the plugin this
```md
some vec $\begin{pmatrix}1\\2\\3\end{pmatrix}$.
```

renders as
<img width="214" alt="image" src="https://github.com/fenjalien/obsidian-typst/assets/24441708/26b8a322-f515-4eec-8e0a-dc078753fef2">

**Comment by fenjalien** [comment]
As of version 0.9 the output SVG's size is in `em` which should scale with the font size of the line it is on including headings. This does highlight another issue of the base line but that should be discussed in a new issue.

> I guess related is:
> 
> ```
> some vec $vec(1,2,3)$.
> ```
> ...

@joleeee This is related to #17, please discuss it there
