### ISSUE TITLE
Text color doesn't sync to theme

### ISSUE THREAD

**Issue by yonatankremer** [fenjalien/obsidian-typst#47]
As far as I'm aware of, the only way to change text color is manually using a set rule. I'd like the rendered text to sync to the current theme's (+light/dark mode) text color, or at least a way to manually set different colors for light, dark mode

**Comment by fenjalien** [comment]
As stated in the [Preambles](https://github.com/fenjalien/obsidian-typst?tab=readme-ov-file#preambles) section in the readme, there is a `THEME` variable that will be either "light" or "dark". You can setup a simple conditional if statement to check the variable and set the text color accordingly.

Note that when changing between light and dark mode, you'll have to refresh the already rendered parts. They won't automatically update as I'm not aware of anyway to detect the change.

If you are using the SVG output it might be possible to add custom CSS that targets the outputted svg and changes the text color accordingly.

**Comment by yonatankremer** [comment]
gotcha. sorry for my impatience haha, I'm very thankful. Not sure if it's intentional, but the inline math works correctly with rtl lines - even raw typst requires a show rule to make that work :)
