### ISSUE TITLE
Inline math limited height

### ISSUE THREAD

**Issue by yonatankremer** [fenjalien/obsidian-typst#48]
<img width="243" alt="Screenshot 2024-05-09 at 7 34 25 PM" src="https://github.com/fenjalien/obsidian-typst/assets/133390605/1d437821-5972-4ba7-b542-abf7669085c5">

Inner-typst rules seem to be able to change equation block "frame", but the inline ones stay constatnt.

last one I swear tsym man (or... woman?)

**Comment by fenjalien** [comment]
Inline equations are restricted to the height of a line as detailed in #17. Closing this as a duplicate, please reopen with more details if you think it is not.
