### ISSUE TITLE
Inline fractions pt.2

### ISSUE THREAD

**Issue by yonatankremer** [fenjalien/obsidian-typst#49]
I am aware by now that inline fractions cutting off is an obsidian issue. Because of that, I'd like to use x/y fraction formatting inline, regular one in blocks. The former is done through setting text(fractions: true). I tried to write a set rule, but no matter what I do it doesn't seem to differentiate inlines and blocks.

**Comment by fenjalien** [comment]
`text(fracitons: true)` has nothing to do with math mode, its a font feature toggle. Please read the documentation again: https://typst.app/docs/reference/text/text/#parameters-fractions

The following code should do what you want:
```
#show math.equation.where(block: false): it => {
  show math.frac: it => $it.num \/ it.denom$
  it
}

$1/2$
$ 1/2 $
```
![image](https://github.com/fenjalien/obsidian-typst/assets/34489450/ecfd41fd-2dcc-4f75-a631-3e113f12f49b)

In the future please only open issues that are directly related to the plugin, seek elsewhere regarding help for the Typst langauge.
