### ISSUE TITLE
[Bug]: Typst output some strange code triggering Dataview report Error

### ISSUE THREAD

**Issue by xjxl520303** [fenjalien/obsidian-typst#58]
See Dataview [Issue 2379](https://github.com/blacksmithgu/obsidian-dataview/issues/2379)

**Comment by d-kaue** [comment]
I think you're missing some [backtick](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Code+blocks) when closing the codeblock.

Make sure if you are in [Source mode](https://help.obsidian.md/Editing+and+formatting/Edit+and+preview+Markdown#Source+mode) to see these symbols properly.

**Comment by xjxl520303** [comment]
> I think you're missing some [backtick](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Code+blocks) when closing the codeblock.
> 
> Make sure if you are in [Source mode](https://help.obsidian.md/Editing+and+formatting/Edit+and+preview+Markdown#Source+mode) to see these symbols properly.

Yes, you're right. It works in **Source mode**, but when I switched to **View mode** still trigger it again. Unless I closed Dataview plugin.

**Comment by d-kaue** [comment]
> It works in **Source mode**, but when I switched to **View mode** still trigger it again.

In Source mode the codeblocks are not rendered.

In the note you're in, do you only have the typst codeblock? Can you provide an example where I can reproduce it?

**Comment by xjxl520303** [comment]
@d-kaue Sorry, last I found it still the Dataview's bug, when I create an empty vault and only download Dataview plugin, I was Reproducing the bug.

**Comment by d-kaue** [comment]
> @d-kaue Sorry, last I found it still the Dataview's bug, when I create an empty vault and only download Dataview plugin, I was Reproducing the bug.

@xjxl520303, I have been able to reproduce the same error and I think I know what could be causing it.

This is because the Dataview is trying to validate the `=` with an [inline query](https://blacksmithgu.github.io/obsidian-dataview/queries/dql-js-inline/#inline-dql).

Try to disable the "Code block inline queries" option in the Dataview settings, this should fix it.
