### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'compile_svg')

### ISSUE THREAD

**Issue by Schabolon** [fenjalien/obsidian-typst#59]
I just updated Obsidian to v1.6.5 and now `TypeError: Cannot read properties of undefined (reading 'compile_svg')` gets displayed for every typst-field.
This happens for math-fields (with `$` or `$$`) and code-blocks.
I am running linux.

Obsidian Version: v1.6.5

**Comment by fenjalien** [comment]
I can't reproduce this on Windows but I don't have a Linux machine. Is the same issue present on a new vault with just this plugin installed, with a note with only a typst block?

**Comment by Schabolon** [comment]
Yes, the same thing happens in a new vault with only the obsidian-typst plugin installed:
![image](https://github.com/fenjalien/obsidian-typst/assets/31383697/5d4a3732-3835-4aff-a887-71e93f04e3dc)
(in this case `compile_image`, on my other vault I use svg)

Screenshot of the console in the new vault:
![image](https://github.com/fenjalien/obsidian-typst/assets/31383697/66708571-c8f3-4f76-bf9f-5170857099d1)

If you need any more information feel free to reach out.

**Comment by fenjalien** [comment]
Welll shoot, I've just updated my Obsidian installer to 1.6.5 and it looks like something is wrong with the webassembly in the web worker. This is a pretty serious problem...

**Comment by d-kaue** [comment]
> Welll shoot, I've just updated my Obsidian installer to 1.6.5 and it looks like something is wrong with the webassembly in the web worker. This is a pretty serious problem...

I don't know about web assembly, what I can help with is simply opinionated.

According to the [changelog version 1.6.5](https://obsidian.md/changelog/2024-06-25-desktop-v1.6.5/), the installer is using Electron v30.1.2, and currently has a WebWorker related fix in [Electron v31.1.0](https://releases.electronjs.org/release/v31.1.0).

Is there any connection?

**Comment by aik2mlj** [comment]
Any update on this issue? Same on my Linux with Obsidian 1.6.5.

**Comment by Xemay** [comment]
I installed electron 31 and changed version in obsidian start script. Now it works well

**Comment by OverHash** [comment]
I've been doing some debugging.

Relevant code that causes the error seems to be [here](https://github.com/rustwasm/wasm-bindgen/blob/cdcbaf1a75d3e89494bbaa46890791094018e386/crates/cli-support/src/js/mod.rs#L807-L840), with specific focus on [line 831](https://github.com/rustwasm/wasm-bindgen/blob/cdcbaf1a75d3e89494bbaa46890791094018e386/crates/cli-support/src/js/mod.rs#L831) where we instantiate.

My initial findings make it seem as though the type of `module` is a `Response`, but there is no global `Response` object. Still investigating...

**Comment by OverHash** [comment]
To add to my response above, I was able to patch the code produced by `wasm-pack` to become:
```js
module = await module.arrayBuffer();
const instance = await WebAssembly.instantiate(module, imports);
```
which makes everything work :D

I'm really not sure where the fix for this should go. I'm really not sure why `Response` is an empty object in the Obsidian JS environment, yet there seems to be something which represents a `Response` returned by `await input` inside the `__wbg_init` function.

---

It looks like `__wbg_init` is called with `input = "blob:app://obsidian.md/becf8bb6-c8c3-4e36-b2dc-f1041cb57454"` (a string). `__wbg_init` will then call `input = fetch(input);` to fetch the wasm. This seems to return a `Promise<Response<...>>` object, which `__wbg_init` will only call `await` on, leaving us with a `Response<...>`. However, it looks like the wasm runner expects it to be an array buffer by this point.

Really not sure where to go from here for getting a more stable fix in!

**Comment by aik2mlj** [comment]
I just updated to Obsidian 1.6.7 (on arch linux) and this issue seems gone.

**Comment by OverHash** [comment]
I did some more testing and it looks like inside `main.ts`, the global `Response` exists (and is of type `function`).

However, inside `compiler.worker.ts`, the type of `Response` is `undefined`.

**Comment by OverHash** [comment]
Just put up a PR which should patch this issue! Would love anyone to test it out. You'll need to build the plugin locally:
1. Clone the repository
2. `npm install`
3. `npm run wasm-build`
4. Copy the `main.js` file over to the relevant Obsidian plugin folder, replacing the existing one.

**Comment by ghareebishere** [comment]
@OverHash 
can you provide a build of it? 
i have no experience in WASM and faced much errors while building it myself

**Comment by OverHash** [comment]
Hey @ghareebishere, here's my build. I would, of course, recommend that you build yourself if you can.

[main.zip](https://github.com/user-attachments/files/16633084/main.zip)

**Comment by d-kaue** [comment]
The Typst Renderer is no longer broken in Obsidian 1.7.4.
To get it working you need to update the **Installer** to version 1.7.4, here's the [download page](https://obsidian.md/download).

**Comment by Schabolon** [comment]
For me it is working with Obsidian 1.7.4 as well.
Closing the issue.
